dist: trusty
sudo: require
language: cpp
compiler: clang
os: 
    - linux
env:
  - CXX_COMPILER=/usr/bin/clang++-6.0 CC_COMPILER=/usr/bin/clang-6.0
  - CXX_COMPILER=gcc++-7 CC_COMPILER=gcc-7
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-6.0
      - ubuntu-toolchain-r-test
    packages:
      - ninja-build
      - clang-6.0
      - clang++-6.0
      - g++-7
      - gcc-7
      - cppcheck
      - clang-format-6.0
      - libglu1-mesa-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - xorg-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libfreeimage-dev
      - libglew-dev
script:
    - export CC=${CC_COMPILER}
    - export CXX=${CXX_COMPILER}
    - ./travis.sh
