dist: trusty
sudo: require
language: cpp
compiler: clang
os: 
    - linux
env:
  - CXX_COMPILER=/usr/bin/clang++-6.0 CC_COMPILER=/usr/bin/clang-6.0
  - CXX_COMPILER=gcc++-7 CC_COMPILELR=gcc-7
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-6.0
      - ubuntu-toolchain-r-test
    packages:
      - ninja-build
      - clang-6.0
      - clang++-6.0
      - g++-7
      - gcc-7
      - cppcheck
      - clang-format-6.0
      - libglu1-mesa-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - xorg-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libfreeimage-dev
      - libglew-dev
script:
    - sudo apt-get install --reinstall dpkg
    - curl http://http.us.debian.org/debian/pool/main/w/wayland/libwayland-client0_1.14.0-2_amd64.deb -O
    - sudo dpkg -i libwayland-client0_1.14.0-2_amd64.deb || true
    - curl http://http.us.debian.org/debian/pool/main/w/wayland/libwayland-server0_1.14.0-2_amd64.deb -O
    - sudo dpkg -i libwayland-server0_1.14.0-2_amd64.deb || true
    - curl http://http.us.debian.org/debian/pool/main/libd/libdrm/libdrm-common_2.4.91-2_all.deb -O
    - sudo dpkg -i libdrm-common_2.4.91-2_all.deb || true
    - curl http://http.us.debian.org/debian/pool/main/libd/libdrm/libdrm2_2.4.91-2_amd64.deb -O
    - sudo dpkg -i libdrm2_2.4.91-2_amd64.deb || true
    - curl http://http.us.debian.org/debian/pool/main/m/mesa/libgbm1_17.3.9-1_amd64.deb -O
    - sudo dpkg -i libgbm1_17.3.9-1_amd64.deb || true
    - curl http://http.us.debian.org/debian/pool/main/libx/libxkbcommon/libxkbcommon0_0.8.0-1_amd64.deb -O
    - sudo dpkg -i libxkbcommon0_0.8.0-1_amd64.deb || true
    - curl http://http.us.debian.org/debian/pool/main/libx/libxkbcommon/libxkbcommon-dev_0.8.0-1_amd64.deb -O
    - sudo dpkg -i libxkbcommon-dev_0.8.0-1_amd64.deb || true
    - curl http://http.us.debian.org/debian/pool/main/m/mesa/libegl-mesa0_17.3.9-1_amd64.deb -O
    - sudo dpkg -i libegl-mesa0_17.3.9-1_amd64.deb || true
    - curl http://http.us.debian.org/debian/pool/main/s/sndio/libsndio6.1_1.1.0-3_amd64.deb -O
    - sudo dpkg -i libsndio6.1_1.1.0-3_amd64.deb || true
    - curl http://http.us.debian.org/debian/pool/main/s/sndio/libsndio-dev_1.1.0-3_amd64.deb -O
    - sudo dpkg -i libsndio-dev_1.1.0-3_amd64.deb || true
    - curl http://http.us.debian.org/debian/pool/main/libs/libsdl2/libsdl2-dev_2.0.8+dfsg1-1_amd64.deb -O
    - sudo dpkg -i libsdl2-dev_2.0.8+dfsg1-1_amd64.deb || true
    - curl http://http.us.debian.org/debian/pool/main/libs/libsdl2/libsdl2-2.0-0_2.0.8+dfsg1-1_amd64.deb -O
    - sudo dpkg -i libsdl2-2.0-0_2.0.8+dfsg1-1_amd64.deb || true
    - export CC=${CC_COMPILER}
    - export CXX=${CXX_COMPILER}
    - mkdir release && cd release && cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release && time ninja OrionUO_unity -j8
    - file ./OrionUO/unity/OrionUO
    #- ./OrionUO/unity/OrionUO --headless
    - cd ..
    - mkdir debug && cd debug && cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Debug && time ninja OrionUO_unity -j8
    - file ./OrionUO/unity/OrionUO
    #- ./OrionUO/unity/OrionUO --headless
